# Generated by Django 6.0.4 on 2026-04-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("short_description", models.TextField()),
                ("full_description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="projects/")),
                ("tech_stack", models.JSONField(default=list)),
                ("github_link", models.URLField(blank=True)),
                ("live_link", models.URLField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                ("category", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
