# Generated by Django 6.0.4 on 2026-04-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("badge", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="case_studies/")),
                ("metrics", models.JSONField(default=dict)),
                ("sections", models.JSONField(default=dict)),
                ("tech_stack", models.JSONField(default=list)),
                ("result", models.TextField(blank=True)),
                ("live_link", models.URLField(blank=True)),
                ("github_link", models.URLField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
