# Generated by Django 6.0.4 on 2026-04-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_casestudy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casestudy",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["ordering", "-created_at"]},
        ),
        migrations.AddField(
            model_name="casestudy",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="badge",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="case_studies/"),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="metrics",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="sections",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="tech_stack",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="tech_stack",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
