# Generated by Django 6.0.4 on 2026-04-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=100)),
                ("skills", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["ordering"],
                "abstract": False,
            },
        ),
    ]
