# Generated by Django 6.0.4 on 2026-04-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skillcategory",
            options={
                "ordering": ["ordering", "title"],
                "verbose_name_plural": "Skill Categories",
            },
        ),
        migrations.RemoveField(
            model_name="skillcategory",
            name="icon",
        ),
        migrations.AddField(
            model_name="skillcategory",
            name="icon_name",
            field=models.CharField(
                default="default-icon",
                help_text="Frontend will map this icon name.",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="skillcategory",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
