# Generated by Django 6.0.4 on 2026-04-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="resume/")),
                ("is_active", models.BooleanField(default=True)),
                ("download_count", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
