# Generated by Django 6.0.4 on 2026-04-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resume",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="resume",
            name="title",
            field=models.CharField(default="Current Resume", max_length=100),
        ),
        migrations.AlterField(
            model_name="resume",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
