# Generated by Django 6.0.4 on 2026-04-15 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitHubStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contributions_count", models.PositiveIntegerField(default=0)),
                ("repositories_count", models.PositiveIntegerField(default=0)),
                ("stars_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "GitHub Stats",
                "verbose_name_plural": "GitHub Stats",
            },
        ),
        migrations.CreateModel(
            name="TopRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("stars", models.PositiveIntegerField(default=0)),
                ("tech_stack", models.JSONField(blank=True, default=list)),
                (
                    "github_stats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_repositories",
                        to="github.githubstats",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Top Repositories",
                "ordering": ["ordering", "name"],
            },
        ),
    ]
