# Generated by Django 6.0.4 on 2026-04-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("headline", models.CharField(max_length=255)),
                ("short_intro", models.TextField()),
                ("profile_image", models.ImageField(upload_to="profile/")),
                ("availability", models.CharField(blank=True, max_length=100)),
                ("footer_text", models.TextField(blank=True)),
                ("contact_cta", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
