# Generated by Django 6.0.4 on 2026-04-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="is_replied",
            field=models.BooleanField(default=False),
        ),
    ]
