# Generated by Django 6.0.4 on 2026-04-15 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timelineitem",
            options={"ordering": ["ordering", "-created_at"]},
        ),
        migrations.RemoveField(
            model_name="timelineitem",
            name="type",
        ),
        migrations.AddField(
            model_name="timelineitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timelineitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("learning", "Learning"),
                    ("experience", "Experience"),
                ],
                default="experience",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="timelineitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
