# Generated by Django 6.0.4 on 2026-04-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sociallink",
            options={"ordering": ["ordering", "name"]},
        ),
        migrations.AddField(
            model_name="sociallink",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("linkedin", "LinkedIn"),
                    ("email", "Email"),
                    ("portfolio", "Portfolio"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="url",
            field=models.CharField(max_length=255),
        ),
    ]
